# Generated by Django 5.2.8 on 2025-11-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suggestion_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KatahoWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('plus_code', models.CharField(blank=True, max_length=20, null=True)),
                ('kataho_code', models.CharField(max_length=255)),
                ('roman_code', models.CharField(blank=True, max_length=255, null=True)),
                ('hint', models.CharField(blank=True, max_length=255, null=True)),
                ('kid', models.IntegerField(blank=True, null=True)),
                ('hints', models.JSONField(blank=True, null=True)),
                ('meanings', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('kataho_code', 'roman_code')},
            },
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
